---
title: "R Notebook"
output: html_notebook
---

# Loading Libraries

```{r message=FALSE, warning=FALSE}
load_packages <- c("ggplot2","car","Hmisc","ROCR","caret","dummies","caTools",
                   "MASS", "gridExtra", "tidyverse", "e1071")
#load the packages
lapply(load_packages,require,character.only = TRUE)
```

# Reading in Data

```{r message=FALSE, warning=FALSE}
germanRaw <- read.csv("german.csv")
```

```{r}
prop.table(table(germanRaw$Default_status))

```

# Data cleansing

Lets cap/floor some numerics to improve stability

## Credit Amount

```{r}
germanRaw$Credit.amount <- as.double(germanRaw$Credit.amount)
boxplot(germanRaw$Credit.amount)
q92 <- quantile(germanRaw$Credit.amount, 0.92)
germanRaw$Credit.amount[which(germanRaw$Credit.amount > q92)] <- q92
boxplot(germanRaw$Credit.amount)

germanRaw$Age.in.Years <- as.double(germanRaw$Age.in.Years)

```

## Age

```{r}
germanRaw$Age.in.Years <- as.double(germanRaw$Age.in.Years)
boxplot(germanRaw$Age.in.Years)
q97 <- quantile(germanRaw$Age.in.Years, 0.97)
germanRaw$Age.in.Years[which(germanRaw$Age.in.Years > q97)] <- q97
boxplot(germanRaw$Age.in.Years)
```

## Ordering factors

```{r}
germanRaw <- germanRaw %>%
             map_if(is.factor, fct_infreq) %>%
             as.data.frame()
```



# EDA
## Univariate Analysis

```{r}
plot_credit_history <- ggplot(germanRaw,
                              aes(x = Credit.history,
                                  fill = factor(Default_status))) +
                       geom_bar() +
                       guides(fill = FALSE)


plot_loan_purpose <- ggplot(germanRaw,
                            aes(x = Credit.history,
                                fill = factor(Default_status))) + 
                     geom_bar() +
                     guides(fill = FALSE)


plot_credit_amount <- ggplot(germanRaw,
                             aes(x = Credit.amount,
                                 fill = factor(Default_status)))  + 
                      geom_histogram(binwidth = 500) + 
                      guides(fill=FALSE)


plot_installment_rate <- ggplot(germanRaw,
                                aes(x = Installment.rate.in.percentage.of.disposable.income,
                                    fill = factor(Default_status))) +
                         geom_bar() + 
                         scale_fill_discrete(labels=c("Good","Bad"))


grid.arrange(plot_credit_history,
             plot_loan_purpose,
             plot_credit_history,
             plot_installment_rate, ncol=2,
             top = "Univariate Analysis")



loan_propery <-  ggplot(germanRaw, 
                        aes(x = Property, 
                            fill = factor(Default_status))) + 
                  geom_bar() +
                  guides(fill=FALSE)
 
#plot housing                           
loan_housing <-  ggplot(germanRaw,
                        aes(x = Housing., 
                            fill = factor(Default_status))) + 
                 geom_bar() +
                 guides(fill=FALSE)

#plot loan job
loan_job <-  ggplot(germanRaw,
                    aes(x = Job_status,
                        fill = factor(Default_status))) +
            geom_bar() +
            guides(fill = FALSE)

#plot loan telephone
loan_telephone <- ggplot(germanRaw,
                         aes(x = Telephone.,
                             fill = factor(Default_status))) +
                  geom_bar() +
                  guides(fill = guide_legend(reverse = TRUE)) +
                  labs(fill = 'Loan status') + 
                  scale_fill_discrete(labels = c("Good", "Bad"))

grid.arrange(loan_housing,loan_job,
             loan_propery,loan_telephone, ncol=2,
             top = "Univariate Analysis")

#plot checking account
loan_checking_account <-  ggplot(germanRaw,
                                 aes(x = Status.of.existing.checking.account,
                                     fill = factor(Default_status))) +
                          geom_bar() +
                          guides(fill = FALSE)

#plot savings bonds
loan_savings_bonds <-ggplot(germanRaw,
                            aes(x = Savings.account.bonds,
                                 fill = factor(Default_status))) +
                    geom_bar() +
                    guides(fill = FALSE)

#plot loan duration
loan_duration <- ggplot(germanRaw,
                        aes(x = Duration.in.month,
                            fill = factor(Default_status))) +
                 geom_histogram(binwidth = 5) +
                 guides(fill = FALSE)


#plot loan other debtors
loan_debtors <-ggplot(germanRaw,
                      aes(x = Other.debtors...guarantors,
                          fill = factor(Default_status))) +
               geom_bar() +
               guides(fill = guide_legend(reverse = TRUE)) +
               labs(fill = 'Loan status') +
  scale_fill_discrete(labels = c("Good", "Bad"))


grid.arrange(loan_checking_account,loan_debtors,loan_duration,
             loan_savings_bonds,ncol=2,top = "Univariate Analysis")

```

Creating dummy variables
```{r}
germanFct <- germanRaw[ , map(germanRaw, class) == "factor"]
germanFct$Default_status <- germanRaw$Default_status

#create dummy variables for the factor variables using dummies package
germanRaw_dummy <- model.matrix(Default_status ~ ., germanFct)
#Remove the original character variables from the dataframe
germanNonFct <- germanRaw[ , map(germanRaw, class) != "factor"]
#Bind the german credit dataframe with dummy variables dataframe
germanDummy <- cbind(germanNonFct, germanRaw_dummy)
germanDummy$Default_status <- as.factor(germanDummy$Default_status)
germanDummy$Default_status <- germanDummy$Default_status %>%
                              fct_recode(good = "1", bad = "0")
```


# Model development

Lets create test/train splits using `caret`

```{r}
ind <- createDataPartition(germanDummy$Default_status,
                           p = 0.75,
                           list = FALSE)

german_train <- germanDummy[ind, , drop = FALSE]
german_test <- germanDummy[-ind, ,drop = FALSE]
```

Lets set up the train control to do 10-fold cross-validation

```{r}
tc <- trainControl("cv",
                   10,
                   savePredictions = TRUE)
```


Fitting the model

```{r}
fit <- train(
              Default_status ~ .,
              data      = germanDummy,
              method    = "glm"    ,
              family    = binomial ,
              trControl = tc
            )

test_reg_cv_model <- train(Default_status ~ .,
                           data = german_train,
                           method = "glmboost", 
                           trControl = rctrl1)

```



```{r}
pred <- predict(fit$finalModel, german_test, type = "response")
fitpredt <- function(t) factor(ifelse(pred > t , 1,0))
confusionMatrix(fitpredt(0.3),german_test$Default_status)

```